### ISSUE TITLE
gMAM for the Maier-Steiner model

### ISSUE THREAD

**Issue by oameye** [JuliaDynamics/CriticalTransitions.jl#11]
I am working on an example notebook for the Maier-Steiner model.
I am trying to reproduce Figure 1 from the [paper](https://arxiv.org/pdf/1604.03818.pdf).
![image](https://github.com/JuliaDynamics/CriticalTransitions.jl/assets/57623933/a82e63c6-a53a-4c3c-91bc-4a6489e91948)
 However, it does not seem that the implemented `geometric_min_action_method` gives the right result.  Am I doing something wrong here:
```julia
using CriticalTransition, StaticArrays, LinearAlgebra
using CairoMakie

function meier_stein!(du, u, p, t) # in-place
    x, y = u
    du[1] = x-x^3 -10*x*y^2
    du[2] = -(1+x^2)*y
end
function meier_stein(u, p, t) # in-place
    x, y = u
    dx = x-x^3 -10*x*y^2
    dy = -(1+x^2)*y
    SA[dx, dy]
end
σ = 0.25
sys = StochSystem(meier_stein, [], zeros(2), σ, idfunc, nothing, I(2), "WhiteGauss")

bmin = [-1.5, -0.6]; bmax = [1.5, 0.6]
fp, eig, stab = fixedpoints(sys, bmin, bmax)
stable_fp = fp[stab]

gm = geometric_min_action_method(sys, fp[stab][1], fp[stab][2], N=50, maxiter=100)
path  = gm[1][end]

res = 100
u_min = -1.5; u_max = 1.5;
v_min = -0.5; v_max = 0.5
u_range = range(u_min, u_max, length = res)
v_range = range(v_min, v_max, length = res)

du(u, v) =   u-u^3 -10*u*v^2
dv(u, v) = -(1+u^2)*v
odeSol(u, v) = Point2f(du(u, v), dv(u, v))

z = [log(sqrt(du(x, y)^2 + dv(x, y)^2)) for x in u_range, y in v_range]
zmin, zmax = minimum(z), maximum(z)

fig = Figure(size = (600, 400), fontsize =13)
ax = Axis(fig[1, 1], xlabel = "u", ylabel = "v", aspect=1.4,
    xgridcolor = :transparent, ygridcolor = :transparent,
    ylabelrotation = 0)

streamplot!(ax, odeSol, (u_min, u_max), (v_min, v_max);
    gridsize = (20, 20), arrow_size = 10, stepsize = 0.01,
    colormap = [:black, :black]
    )
colgap!(fig.layout, 7)
limits!(u_min,u_max,v_min,v_max)
fig

[scatter!(ax, Point(fp[i]), color = stab[i] > 0 ? :red : :dodgerblue,
    markersize = 10) for i in eachindex(fp)]
    
lines!(ax, path  )    
fig
```
![image](https://github.com/JuliaDynamics/CriticalTransitions.jl/assets/57623933/d546ae94-7bf2-478b-8bb1-dac3c249c639)

**Comment by reykboerner** [comment]
Thanks for trying this! I tweaked your code a bit and found two things

- gMAM does not guarantee finding the global minimum. In your code the path is initialized as a straight line which I think could be a local minimum for the Maier-Stein model (haven't verified). If I initialize the path as a parabola, it finds the correct minimizer.
- The minimization procedure seems quite sensitive to the hyperparameters such as number of path points. If I change `N=50` to `N=30`, it also finds the right minimizer.

Currently our code formulates the minimization problem and simply passes it to Optim - to get more robust results with respect to the hyperparameters we might need to tweak the Optim default settings a bit more.

Here's my code:

```julia
using CriticalTransitions, StaticArrays, LinearAlgebra
#using CairoMakie
using PyPlot

function meier_stein!(du, u, p, t) # in-place
    x, y = u
    du[1] = x-x^3 -10*x*y^2
    du[2] = -(1+x^2)*y
end
function meier_stein(u, p, t) # in-place
    x, y = u
    dx = x-x^3 -10*x*y^2
    dy = -(1+x^2)*y
    SA[dx, dy]
end
σ = 0.25
sys = StochSystem(meier_stein, [], zeros(2), σ, idfunc, nothing, I(2), "WhiteGauss")

bmin = [-1.5, -0.6]; bmax = [1.5, 0.6]
fp, eig, stab = fixedpoints(sys, bmin, bmax)
stable_fp = fp[stab]

# initial path: parabola
xx = range(-1.0,1.0, length=30)
yy = 0.3 .* (- xx .^ 2 .+ 1)
init = Matrix([xx yy]')

# initialize from straight line (50 points)
gm = geometric_min_action_method(sys, fp[stab][1], fp[stab][2], N=50, maxiter=200, converge=1e-7)
path  = gm[1][end]

# initialize from straight line (30 points)
gm2 = geometric_min_action_method(sys, fp[stab][1], fp[stab][2], N=30, maxiter=200, converge=1e-7)
path2  = gm2[1][end]

gm3 = geometric_min_action_method(sys, init, maxiter=200, converge=1e-7)
path3 = gm3[1][end]


begin
    fig, ax = subplots(dpi=150)
    ax.plot(xx,yy, ls="--", c="gray")
    ax.plot(path[1,:], path[2,:], label="Path, S=$(round(gm[2][end], digits=5))")
    ax.plot(path2[1,:], path2[2,:], label="Path 2, S=$(round(gm2[2][end], digits=5))")
    ax.plot(path3[1,:], path3[2,:], label="Path 3, S=$(round(gm3[2][end], digits=5))")
    ax.legend(title="S = Action value")
    display(gcf())
end
```

<img width="480" alt="image" src="https://github.com/JuliaDynamics/CriticalTransitions.jl/assets/47892693/211aedda-671e-433c-9b15-3cb3df861372">

**Comment by oameye** [comment]
Thank you very much for the help! It totally missed in the documentation that you can choose your initial path. I will highlight this in the example notebook.

I also think the straight line is a sort of local minima. It is at least the naive path (heteroclinic orbit) one would think the system takes without using gMAM.
