### ISSUE TITLE
EM() as the default solver?

### ISSUE THREAD

**Issue by oameye** [JuliaDynamics/CriticalTransitions.jl#21]
Why do we use `EM()` as the default solver? From the example of [StochasticDiffEq.jl docs](https://docs.sciml.ai/DiffEqDocs/stable/tutorials/sde_example/) this method seems to be prone to errors. The same can be said for `Euler()` as the deterministic solver.
![image](https://github.com/JuliaDynamics/CriticalTransitions.jl/assets/57623933/95ecd909-a2f8-47bd-921a-3ef8bcf20abc)

**Comment by reykboerner** [comment]
Indeed Euler-Maruyama can be inadequate especially for large step sizes, but it is still so commonly used that one could argue it is still a reasonable default solver. Users would potentially be less familiar with the other SDE solvers. Which one would you use?

For ODEs I argee that one could replace Euler by something like `RK4()` or `DP5()`.

**Comment by oameye** [comment]
`DP5()` is dangerous as it isn't useful for damped systems. I would use the default solvers that SciML uses which would be `Tsit5()` and `SRIW1()` I think.

**Comment by reykboerner** [comment]
Hmm, `Tsit5()` caused some problems when used with DynamicalSystems.jl (see [this issue](https://github.com/JuliaDynamics/Attractors.jl/issues/33)). But I agree that it's best to go with established defaults if we don't stick with the most basic defaults.
