### ISSUE TITLE
Use SteadyStateProblem

### ISSUE THREAD

**Issue by oameye** [JuliaDynamics/CriticalTransitions.jl#24]
It can be a good idea to use SteadyStateProblem in the `equilib` function instead of `Callback` in combination with `ODEProblem`. In the background this will be basically be the same as now, however, it will give probably better warning, output, retcode. A benchmark/comparison is here in order.

https://github.com/JuliaDynamics/CriticalTransitions.jl/blob/105ef80c4dfd5a8be2f106078a09f4499e6dce23/src/systemanalysis/stability.jl#L15-L29

**Comment by reykboerner** [comment]
We were actually considering to remove the `equilib` function altogether. With Attractors.jl or `fixedpoints` in ChaosTools.jl there are much better ways to find attractors and `equilib` as written above is just prone to stop in quasi-equilibria.

**Comment by oameye** [comment]
I think keeping it is still very useful, but I agree we should add more methods, which is just the writing interface for `Stochsystem` which in the background juts translates to `CoupledODEs` struct

In `HarmonicBalance.jl` use a method called homotopyContinuation which guarantees to find all critical points (attractors, repellers and saddle nodes). It has been very effective for us.
